Repository PontoSprint4/br.com.proway.senior.controlePonto, pull requests merged in 2021-05, with the labels that each got.

#42 refatoracao dos endpoints de adicionar e remover pessoas do turno
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/api/TurnoAPI.java
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/model/ListaDePessoas.java
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/services/TurnoService.java
Labels: API, Backend, Melhoras

#44 TurnoDTO na madrugada
  InsomniaControleDePontoJornada.json
  InsomniaControleDePontoPonto.json
  README.md
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/model/TurnoDTO.java
  SpringControlePonto/src/main/java/br/com/proway/senior/utils/FormatacaoDeTempo.java
  SpringControlePonto/src/test/java/br/com/proway/senior/controlePonto/services/PontoServiceTest.java
  SpringControlePonto/src/test/java/br/com/proway/senior/utils/FormatacaoDeTempoTest.java
Labels: Backend, Nova funcionalidade, bug

#49 Resolvendo Problemas nos Updates do DAOGenerico com Statement
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/DAO/GenericDAO.java
Labels: Backend, bug
