Repository PontoSprint4/br.com.proway.senior.controlePonto, pull requests merged in 2021-06, with the labels that each got.

#67 Front end turno
  projeto-site-1-main/projeto-site-1-main/.gitattributes
  projeto-site-1-main/projeto-site-1-main/LICENSE
  projeto-site-1-main/projeto-site-1-main/README.md
  projeto-site-1-main/projeto-site-1-main/adicionarPessoa.js
  projeto-site-1-main/projeto-site-1-main/button.css
  projeto-site-1-main/projeto-site-1-main/criarTurno.js
  projeto-site-1-main/projeto-site-1-main/deletarPessoaTurno.js
  projeto-site-1-main/projeto-site-1-main/deletarTurno.js
  projeto-site-1-main/projeto-site-1-main/detailsTurno.html
  projeto-site-1-main/projeto-site-1-main/formulario.css
  projeto-site-1-main/projeto-site-1-main/imagens/cabecalho_site.png
  projeto-site-1-main/projeto-site-1-main/imagens/desconhecidoFinal.png
  projeto-site-1-main/projeto-site-1-main/imagens/voltar.png
  projeto-site-1-main/projeto-site-1-main/img.css
  projeto-site-1-main/projeto-site-1-main/index.html
  projeto-site-1-main/projeto-site-1-main/pagina1.html
  projeto-site-1-main/projeto-site-1-main/pagina2.html
  projeto-site-1-main/projeto-site-1-main/pagina3.html
  projeto-site-1-main/projeto-site-1-main/style.css
  projeto-site-1-main/projeto-site-1-main/table.css
Labels: Frontend

#80 Angular ponto
  controle-de-ponto-client/package-lock.json
  controle-de-ponto-client/src/app/app.component.html
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.css
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.html
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.spec.ts
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.ts
  controle-de-ponto-client/src/styles.css
Labels: Frontend

#82 Passado o projeto para angular Tela de JornadaGerencia
  controle-de-ponto-client/package-lock.json
  controle-de-ponto-client/src/app/app.component.html
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.css
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.html
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.spec.ts
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.ts
Labels: Frontend, Nova funcionalidade

#84 Jornada gerencia
  controle-de-ponto-client/.gitignore
  controle-de-ponto-client/angular.json
  controle-de-ponto-client/package-lock.json
  controle-de-ponto-client/package.json
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.css
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.html
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.ts
  controle-de-ponto-client/src/polyfills.ts
Labels: Frontend

#83 Angular jornada listagem
  controle-de-ponto-client/src/app/app.component.html
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.css
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.html
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.spec.ts
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.ts
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.css
  controle-de-ponto-client/src/styles.css
  frontend/JornadaHistorico.html
Labels: Frontend

#85 Bootstrap2 jornada listagem
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.css
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.html
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.ts
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.css
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.html
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.ts
Labels: Frontend

#86 Jornada historico adm
  controle-de-ponto-client/angular.json
  controle-de-ponto-client/src/app/app.component.html
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.css
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.html
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.spec.ts
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.ts
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.css
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.html
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.spec.ts
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.ts
  controle-de-ponto-client/src/app/ponto-criar/ponto-criar.component.css
  controle-de-ponto-client/src/app/ponto-criar/ponto-criar.component.html
  controle-de-ponto-client/src/app/ponto-criar/ponto-criar.component.spec.ts
  controle-de-ponto-client/src/app/ponto-criar/ponto-criar.component.ts
  controle-de-ponto-client/src/app/ponto-crud-listagem/ponto-crud-listagem.component.css
  controle-de-ponto-client/src/app/ponto-editar/ponto-editar.component.css
  controle-de-ponto-client/src/app/ponto-editar/ponto-editar.component.html
  controle-de-ponto-client/src/app/ponto-editar/ponto-editar.component.spec.ts
  controle-de-ponto-client/src/app/ponto-editar/ponto-editar.component.ts
  controle-de-ponto-client/src/index.html
  controle-de-ponto-client/src/styles.css
Labels: Frontend

#92 Rota marcar ponto não necessita de Ponto no body, GetAll de jornada
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/api/JornadaAPI.java
  SpringControlePonto/src/test/java/br/com/proway/senior/controlePonto/api/JornadaAPITest.java
Labels: API, Backend, Boa primeira issue, Melhoras

#93 Backend boogaloo
  .gitignore
  SpringControlePonto/src/main/java/br/com/proway/senior/controlePonto/services/JornadaService.java
  SpringControlePonto/src/test/java/br/com/proway/senior/controlePonto/api/JornadaAPITest.java
  SpringControlePonto/src/test/java/br/com/proway/senior/controlePonto/services/JornadaServiceTest.java
  controle-de-ponto-client/src/app/app-routing.module.ts
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.html
  controle-de-ponto-client/src/app/ponto-marcar/ponto-marcar.component.html
  controle-de-ponto-client/src/app/ponto-marcar/ponto-marcar.component.ts
  controle-de-ponto-client/src/app/turno-index/turno-index.component.html
Labels: API, Backend, Melhoras, Nova funcionalidade

#94 fim turno
  controle-de-ponto-client/src/app/app-routing.module.ts
  controle-de-ponto-client/src/app/app.module.ts
  controle-de-ponto-client/src/app/formulario-criar-turno/formulario-criar-turno.component.css
  controle-de-ponto-client/src/app/formulario-criar-turno/formulario-criar-turno.component.html
  controle-de-ponto-client/src/app/formulario-criar-turno/formulario-criar-turno.component.spec.ts
  controle-de-ponto-client/src/app/formulario-criar-turno/formulario-criar-turno.component.ts
  controle-de-ponto-client/src/app/turno-index/turno-index.component.html
  controle-de-ponto-client/src/app/turno-index/turno-index.component.ts
Labels: Frontend

#95 Em casa teste telas
  controle-de-ponto-client/package-lock.json
  controle-de-ponto-client/src/app/app-routing.module.ts
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.html
  controle-de-ponto-client/src/app/jornada-criar/jornada-criar.component.ts
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.css
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.html
  controle-de-ponto-client/src/app/jornada-crud-listagem-adm/jornada-crud-listagem-adm.component.ts
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.html
  controle-de-ponto-client/src/app/jornada-editar/jornada-editar.component.ts
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.css
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.html
  controle-de-ponto-client/src/app/jornada-listagem/jornada-listagem.component.ts
  controle-de-ponto-client/src/app/jornada.service.spec.ts
  controle-de-ponto-client/src/app/jornada.service.ts
  controle-de-ponto-client/src/app/jornada.ts
  controle-de-ponto-client/src/app/turno.service.ts
Labels: API, Frontend
